server:
  port: 7441

spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        metadata_builder_contributor: kr.cornerstone.global.config.jpa.MariaCustomDialect
        format_sql: true
    generate-ddl: false
    open-in-view: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(dj4rOhQqh84uEe0XuW0+v+pIW4d9g130itQEKoLxYwFC3NnOg1N5bs9yzB8VRcC80Z2HHkmFWhsQMd2nqkY+bunRKZz6Fww/nfKWQUsYfoT1QZD7q5nvBUcepO9fBXJkgFjHuwO5yHz1+AL4VjCVCg==)
    username: ENC(0R4troqKh5MY6zy6Y9hrF5SacYNprCp3)
    password: ENC(MOX3fUC8zzzo7O5jPfGKJuecAQLg/qEA)

  sql:
    init:
      mode: always
